server:
  port: ${PORT:8080}
spring:
  jackson:
    serialization:
      failOnEmptyBeans: false
  datasource:
    plataform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://elhqjeivkurtru:ae1c718e8c74e61ce55ecb3b34c26157e08d416c6d078b4ba22e0950e625e476@ec2-18-213-176-229.compute-1.amazonaws.com:5432/dp9vb5inq1l3k?useSSL=false
    #url: jdbc:postgresql://ec2-54-225-237-84.compute-1.amazonaws.com:5432/dadlba8rt8eoru?useSSL=false&sslmode=require
    username: elhqjeivkurtru
    password: ae1c718e8c74e61ce55ecb3b34c26157e08d416c6d078b4ba22e0950e625e476
  h2:
    console:
      enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      temp:
        useJdbcMetadaDefaults: false
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        generateStatistics: true
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
